"""update_images_comment_tag

Revision ID: 0a1ad9eb746d
Revises: 7e37c62857d6
Create Date: 2023-12-12 00:32:00.503617

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0a1ad9eb746d'
down_revision: Union[str, None] = '7e37c62857d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transformed_image_links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('image_id', sa.Integer(), nullable=False),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.Column('transformation_url', sa.String(length=255), nullable=False),
    sa.Column('qr_code_url', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['image_id'], ['images_table.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('transformation_url')
    )
    op.add_column('comments_table', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.drop_column('comments_table', 'crated_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments_table', sa.Column('crated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('comments_table', 'created_at')
    op.drop_table('transformed_image_links')
    # ### end Alembic commands ###
