"""add_relationship_comment_to_images

Revision ID: 8543b9aabb3d
Revises: 0a1ad9eb746d
Create Date: 2023-12-12 01:02:54.183855

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8543b9aabb3d'
down_revision: Union[str, None] = '0a1ad9eb746d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transformed_image_links', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.drop_column('transformed_image_links', 'modified_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transformed_image_links', sa.Column('modified_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('transformed_image_links', 'created_at')
    # ### end Alembic commands ###
